export interface Member {
  id: string;
  name: string;
  email: string;
  role: 'admin' | 'member';
  avatar?: string;
}

export type FinanceScope = 'household' | 'personal';

export interface Transaction {
  id: string;
  type: 'income' | 'expense';
  label: string;
  amount: number;
  currency: string;
  exchangeRate: number;
  baseCurrency: string;
  convertedAmount: number;
  category: string;
  memberId: string;
  date: string;
  notes?: string;
  emoji: string;
  isRecurring?: boolean;
  recurrenceDay?: number;
  recurringSourceId?: string;
  recurringStartMonth?: string;
  recurringEndMonth?: string | null;
  accountId?: string;
  isAutoGenerated?: boolean;
  debtId?: string;
  debtPaymentType?: 'interest' | 'principal' | null;
  scope?: FinanceScope;
  createdBy?: string;
}

export interface Budget {
  id: string;
  category: string;
  limit: number;
  period: 'monthly' | 'yearly';
  emoji: string;
  alertsEnabled: boolean;
  recurring: boolean;
  isRecurring: boolean;
  monthYear?: string;
  startMonth: string;
  endMonth?: string | null;
  scope?: FinanceScope;
  createdBy?: string;
}

export interface SavingsGoal {
  id: string;
  name: string;
  emoji: string;
  target: number;
  currency: string;
  targetDate?: string;
  scope?: FinanceScope;
  createdBy?: string;
}

export interface SavingsDeposit {
  id: string;
  goalId: string;
  amount: number;
  memberId: string;
  date: string;
}

export interface CustomCategory {
  name: string;
  emoji: string;
  type: 'expense' | 'income';
}

export type AccountType = string;

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  currency: string;
  startingBalance: number;
  startingDate: string;
  isArchived: boolean;
  createdAt: string;
  updatedAt: string;
  scope?: FinanceScope;
  createdBy?: string;
}

export const ACCOUNT_TYPES: { value: string; label: string; emoji: string }[] = [
  { value: 'courant', label: 'Compte courant', emoji: '🏦' },
  { value: 'epargne', label: 'Compte épargne', emoji: '🐖' },
  { value: 'pilier3a', label: '3e pilier A', emoji: '🏔️' },
  { value: 'carte_credit', label: 'Carte de crédit', emoji: '💳' },
  { value: 'cash', label: 'Compte cash', emoji: '💵' },
  { value: 'prepaye', label: 'Compte prépayé', emoji: '📱' },
  { value: 'pilier2', label: '2e pilier (LPP)', emoji: '🏛️' },
  { value: 'vacances', label: 'Compte vacances', emoji: '🏖️' },
  { value: 'terme', label: 'Compte à terme', emoji: '⏳' },
  { value: 'autre', label: 'Autres', emoji: '📁' },
];

export interface CustomAccountType {
  value: string;
  label: string;
  emoji: string;
}

export interface Household {
  name: string;
  currency: string;
  createdAt: string;
  plan: string;
  monthlySavingsTarget: number | null;
  members: Member[];
}

export interface AppState {
  isLoggedIn: boolean;
  isOnboarded: boolean;
  currentUser: Member | null;
  household: Household;
  transactions: Transaction[];
  budgets: Budget[];
  savingsGoals: SavingsGoal[];
  savingsDeposits: SavingsDeposit[];
  customCategories: CustomCategory[];
  accounts: Account[];
}

export const EXPENSE_CATEGORIES = [
  'Logement', 'Alimentation', 'Transport', 'Restaurants', 'Loisirs',
  'Shopping', 'Abonnements', 'Santé', 'Famille & Enfants', 'Éducation',
  'Voyages', 'Cadeaux', 'Impôts & Taxes', 'Assurances', 'Animaux',
  'Frais bancaires', 'Autre'
] as const;

export const INCOME_CATEGORIES = [
  'Salaire', 'Freelance', 'Bonus / Prime', 'Revenus locatifs', 'Investissements',
  'Allocations', 'Pension / Retraite', 'Pension alimentaire',
  'Cadeaux / Dons', 'Remboursements', 'Ventes', 'Autre'
] as const;

export const CURRENCIES = [
  // Major
  'EUR', 'USD', 'GBP', 'CHF', 'JPY', 'CAD', 'AUD', 'NZD', 'CNY', 'HKD', 'SGD',
  // Europe
  'SEK', 'NOK', 'DKK', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'HRK', 'ISK', 'RUB', 'UAH', 'TRY',
  // Americas
  'MXN', 'BRL', 'ARS', 'CLP', 'COP', 'PEN', 'UYU', 'BOB', 'PYG', 'VES', 'CRC', 'DOP', 'GTQ', 'HNL', 'JMD', 'TTD', 'BBD', 'BSD',
  // Asia
  'KRW', 'INR', 'IDR', 'MYR', 'THB', 'PHP', 'VND', 'TWD', 'PKR', 'BDT', 'LKR', 'MMK', 'KHR', 'LAK', 'MNT', 'NPR', 'KZT', 'UZS', 'GEL', 'AMD', 'AZN',
  // Middle East
  'AED', 'SAR', 'QAR', 'KWD', 'BHD', 'OMR', 'JOD', 'ILS', 'LBP', 'IQD', 'IRR', 'SYP', 'YER',
  // Africa
  'ZAR', 'EGP', 'NGN', 'KES', 'GHS', 'TZS', 'UGX', 'MAD', 'TND', 'DZD', 'LYD', 'XOF', 'XAF', 'MUR', 'BWP', 'ETB', 'RWF', 'MZN', 'AOA', 'CDF',
  // Oceania
  'FJD', 'PGK', 'WST', 'TOP',
] as const;

// Default exchange rates (relative to EUR) used when creating transactions
export const DEFAULT_EXCHANGE_RATES: Record<string, number> = {
  EUR: 1,
  USD: 0.92,
  GBP: 1.17,
  CHF: 1.05,
  JPY: 0.006,
  CAD: 0.68,
  AUD: 0.60,
  NZD: 0.55,
  CNY: 0.13,
  HKD: 0.12,
  SGD: 0.69,
  SEK: 0.087,
  NOK: 0.086,
  DKK: 0.13,
  PLN: 0.23,
  CZK: 0.040,
  HUF: 0.0026,
  RON: 0.20,
  TRY: 0.027,
  INR: 0.011,
  BRL: 0.17,
  MXN: 0.053,
  ZAR: 0.051,
  KRW: 0.00069,
};

export const CURRENCY_SYMBOLS: Record<string, string> = {
  EUR: '€', USD: '$', GBP: '£', CHF: 'CHF', JPY: '¥', CAD: 'CA$', AUD: 'A$', NZD: 'NZ$',
  CNY: '¥', HKD: 'HK$', SGD: 'S$', SEK: 'kr', NOK: 'kr', DKK: 'kr', PLN: 'zł', CZK: 'Kč',
  HUF: 'Ft', RON: 'lei', TRY: '₺', RUB: '₽', UAH: '₴', MXN: 'MX$', BRL: 'R$', ARS: 'AR$',
  KRW: '₩', INR: '₹', IDR: 'Rp', MYR: 'RM', THB: '฿', PHP: '₱', VND: '₫', TWD: 'NT$',
  PKR: '₨', AED: 'د.إ', SAR: '﷼', QAR: 'ر.ق', KWD: 'د.ك', BHD: 'BD', ILS: '₪',
  ZAR: 'R', EGP: 'E£', NGN: '₦', KES: 'KSh', GHS: 'GH₵', MAD: 'MAD', TND: 'DT',
  FJD: 'FJ$',
};

export const CURRENCY_NAMES: Record<string, string> = {
  EUR: 'Euro', USD: 'Dollar américain', GBP: 'Livre sterling', CHF: 'Franc suisse',
  JPY: 'Yen japonais', CAD: 'Dollar canadien', AUD: 'Dollar australien', NZD: 'Dollar néo-zélandais',
  CNY: 'Yuan chinois', HKD: 'Dollar de Hong Kong', SGD: 'Dollar de Singapour',
  SEK: 'Couronne suédoise', NOK: 'Couronne norvégienne', DKK: 'Couronne danoise',
  PLN: 'Złoty polonais', CZK: 'Couronne tchèque', HUF: 'Forint hongrois',
  RON: 'Leu roumain', BGN: 'Lev bulgare', HRK: 'Kuna croate', ISK: 'Couronne islandaise',
  RUB: 'Rouble russe', UAH: 'Hryvnia ukrainienne', TRY: 'Livre turque',
  MXN: 'Peso mexicain', BRL: 'Réal brésilien', ARS: 'Peso argentin',
  CLP: 'Peso chilien', COP: 'Peso colombien', PEN: 'Sol péruvien', UYU: 'Peso uruguayen',
  KRW: 'Won sud-coréen', INR: 'Roupie indienne', IDR: 'Roupie indonésienne',
  MYR: 'Ringgit malaisien', THB: 'Baht thaïlandais', PHP: 'Peso philippin',
  VND: 'Dong vietnamien', TWD: 'Dollar taïwanais', PKR: 'Roupie pakistanaise',
  BDT: 'Taka bangladais', AED: 'Dirham des EAU', SAR: 'Riyal saoudien',
  QAR: 'Riyal qatarien', KWD: 'Dinar koweïtien', BHD: 'Dinar bahreïni',
  OMR: 'Rial omanais', JOD: 'Dinar jordanien', ILS: 'Shekel israélien',
  ZAR: 'Rand sud-africain', EGP: 'Livre égyptienne', NGN: 'Naira nigérian',
  KES: 'Shilling kényan', GHS: 'Cedi ghanéen', TZS: 'Shilling tanzanien',
  MAD: 'Dirham marocain', TND: 'Dinar tunisien', DZD: 'Dinar algérien',
  XOF: 'Franc CFA (BCEAO)', XAF: 'Franc CFA (BEAC)', MUR: 'Roupie mauricienne',
  FJD: 'Dollar fidjien',
};

export const CATEGORY_EMOJIS: Record<string, string> = {
  Transfert: '🔄',
  Logement: '🏠',
  Alimentation: '🛒',
  Transport: '🚗',
  Restaurants: '🍽️',
  Loisirs: '🎮',
  Shopping: '👗',
  Abonnements: '📱',
  Santé: '💊',
  'Famille & Enfants': '👶',
  'Éducation': '📚',
  Voyages: '✈️',
  Cadeaux: '🎁',
  'Impôts & Taxes': '📋',
  Assurances: '🛡️',
  Animaux: '🐾',
  'Frais bancaires': '💳',
  'Épargne': '💰',
  Salaire: '💻',
  Freelance: '🏆',
  'Bonus / Prime': '🏆',
  'Revenus locatifs': '🏠',
  Investissements: '📈',
  Allocations: '👶',
  'Pension / Retraite': '👴',
  'Pension alimentaire': '👨‍👩‍👧',
  'Cadeaux / Dons': '🎁',
  Remboursements: '💸',
  Ventes: '🛒',
  Autre: '📦',
};

export const EMOJI_LIST = [
  '🛒','🏠','🚗','💊','🎬','🛍️','📱','📚','✈️','🍽️','🔧','📄','💰','💻','📈','🏛️','📌',
  '🎮','🏋️','🐾','👶','🎁','💇','🧹','🔌','📦','🎵','☕','🍕','🎂','💍','🏥','🚌','🚲','⛽','🧾',
];
